/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Sat Feb  1 19:54:46 2025.
 */

#include <string.h>

#include "mcan.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int mcan_m_diag_1_pack(
    uint8_t *dst_p,
    const struct mcan_m_diag_1_t *src_p,
    size_t size)
{
    uint32_t er;
    uint32_t reg_out;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    reg_out = (uint32_t)src_p->reg_out;
    dst_p[0] |= pack_right_shift_u32(reg_out, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(reg_out, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(reg_out, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(reg_out, 0u, 0xffu);
    er = (uint32_t)src_p->er;
    dst_p[4] |= pack_right_shift_u32(er, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(er, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(er, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(er, 0u, 0xffu);

    return (8);
}

int mcan_m_diag_1_unpack(
    struct mcan_m_diag_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t er;
    uint32_t reg_out;

    if (size < 8u) {
        return (-EINVAL);
    }

    reg_out = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    reg_out |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    reg_out |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    reg_out |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->reg_out = (int32_t)reg_out;
    er = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    er |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    er |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    er |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);
    dst_p->er = (int32_t)er;

    return (0);
}

int mcan_m_diag_1_init(struct mcan_m_diag_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_diag_1_t));

    return 0;
}

int32_t mcan_m_diag_1_reg_out_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_diag_1_reg_out_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_diag_1_reg_out_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t mcan_m_diag_1_er_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_diag_1_er_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_diag_1_er_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int mcan_m_command_1_pack(
    uint8_t *dst_p,
    const struct mcan_m_command_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->m_drive_en, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->m_en, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->m_mode, 2u, 0x3cu);

    return (8);
}

int mcan_m_command_1_unpack(
    struct mcan_m_command_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->m_drive_en = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->m_en = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->m_mode = unpack_right_shift_u8(src_p[0], 2u, 0x3cu);

    return (0);
}

int mcan_m_command_1_init(struct mcan_m_command_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_command_1_t));

    return 0;
}

uint8_t mcan_m_command_1_m_drive_en_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_command_1_m_drive_en_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_command_1_m_drive_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcan_m_command_1_m_en_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_command_1_m_en_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_command_1_m_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcan_m_command_1_m_mode_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_command_1_m_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_command_1_m_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int mcan_m_status_1_pack(
    uint8_t *dst_p,
    const struct mcan_m_status_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->m_drive_en, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->m_en, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->m_mode, 2u, 0x3cu);
    dst_p[1] |= pack_left_shift_u8(src_p->m_error, 0u, 0xffu);

    return (8);
}

int mcan_m_status_1_unpack(
    struct mcan_m_status_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->m_drive_en = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->m_en = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->m_mode = unpack_right_shift_u8(src_p[0], 2u, 0x3cu);
    dst_p->m_error = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int mcan_m_status_1_init(struct mcan_m_status_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_status_1_t));

    return 0;
}

uint8_t mcan_m_status_1_m_drive_en_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_status_1_m_drive_en_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_status_1_m_drive_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcan_m_status_1_m_en_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_status_1_m_en_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_status_1_m_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcan_m_status_1_m_mode_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_status_1_m_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_status_1_m_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t mcan_m_status_1_m_error_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_status_1_m_error_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_status_1_m_error_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int mcan_m_ref_1_pack(
    uint8_t *dst_p,
    const struct mcan_m_ref_1_t *src_p,
    size_t size)
{
    uint32_t position;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint32_t)src_p->position;
    dst_p[0] |= pack_right_shift_u32(position, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(position, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(position, 0u, 0xffu);
    velocity = (uint32_t)src_p->velocity;
    dst_p[4] |= pack_right_shift_u32(velocity, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(velocity, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(velocity, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(velocity, 0u, 0xffu);

    return (8);
}

int mcan_m_ref_1_unpack(
    struct mcan_m_ref_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t position;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    position |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    position |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->position = (int32_t)position;
    velocity = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    velocity |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);
    dst_p->velocity = (int32_t)velocity;

    return (0);
}

int mcan_m_ref_1_init(struct mcan_m_ref_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_ref_1_t));

    return 0;
}

int32_t mcan_m_ref_1_position_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_ref_1_position_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_ref_1_position_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t mcan_m_ref_1_velocity_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_ref_1_velocity_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_ref_1_velocity_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int mcan_m_pos_vel_1_pack(
    uint8_t *dst_p,
    const struct mcan_m_pos_vel_1_t *src_p,
    size_t size)
{
    uint32_t position;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint32_t)src_p->position;
    dst_p[0] |= pack_right_shift_u32(position, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(position, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(position, 0u, 0xffu);
    velocity = (uint32_t)src_p->velocity;
    dst_p[4] |= pack_right_shift_u32(velocity, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(velocity, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(velocity, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(velocity, 0u, 0xffu);

    return (8);
}

int mcan_m_pos_vel_1_unpack(
    struct mcan_m_pos_vel_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t position;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    position |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    position |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->position = (int32_t)position;
    velocity = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    velocity |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);
    dst_p->velocity = (int32_t)velocity;

    return (0);
}

int mcan_m_pos_vel_1_init(struct mcan_m_pos_vel_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_pos_vel_1_t));

    return 0;
}

int32_t mcan_m_pos_vel_1_position_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_pos_vel_1_position_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_pos_vel_1_position_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t mcan_m_pos_vel_1_velocity_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_pos_vel_1_velocity_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_pos_vel_1_velocity_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int mcan_m_command_2_pack(
    uint8_t *dst_p,
    const struct mcan_m_command_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->m_drive_en, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->m_en, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->m_mode, 2u, 0x3cu);

    return (8);
}

int mcan_m_command_2_unpack(
    struct mcan_m_command_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->m_drive_en = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->m_en = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->m_mode = unpack_right_shift_u8(src_p[0], 2u, 0x3cu);

    return (0);
}

int mcan_m_command_2_init(struct mcan_m_command_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_command_2_t));

    return 0;
}

uint8_t mcan_m_command_2_m_drive_en_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_command_2_m_drive_en_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_command_2_m_drive_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcan_m_command_2_m_en_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_command_2_m_en_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_command_2_m_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcan_m_command_2_m_mode_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_command_2_m_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_command_2_m_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int mcan_m_status_2_pack(
    uint8_t *dst_p,
    const struct mcan_m_status_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->m_drive_en, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->m_en, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->m_mode, 2u, 0x3cu);
    dst_p[1] |= pack_left_shift_u8(src_p->m_error, 0u, 0xffu);

    return (8);
}

int mcan_m_status_2_unpack(
    struct mcan_m_status_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->m_drive_en = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->m_en = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->m_mode = unpack_right_shift_u8(src_p[0], 2u, 0x3cu);
    dst_p->m_error = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int mcan_m_status_2_init(struct mcan_m_status_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_status_2_t));

    return 0;
}

uint8_t mcan_m_status_2_m_drive_en_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_status_2_m_drive_en_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_status_2_m_drive_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcan_m_status_2_m_en_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_status_2_m_en_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_status_2_m_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcan_m_status_2_m_mode_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_status_2_m_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_status_2_m_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t mcan_m_status_2_m_error_encode(float value)
{
    return (uint8_t)(value);
}

float mcan_m_status_2_m_error_decode(uint8_t value)
{
    return ((float)value);
}

bool mcan_m_status_2_m_error_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int mcan_m_ref_2_pack(
    uint8_t *dst_p,
    const struct mcan_m_ref_2_t *src_p,
    size_t size)
{
    uint32_t position;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint32_t)src_p->position;
    dst_p[0] |= pack_right_shift_u32(position, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(position, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(position, 0u, 0xffu);
    velocity = (uint32_t)src_p->velocity;
    dst_p[4] |= pack_right_shift_u32(velocity, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(velocity, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(velocity, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(velocity, 0u, 0xffu);

    return (8);
}

int mcan_m_ref_2_unpack(
    struct mcan_m_ref_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t position;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    position |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    position |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->position = (int32_t)position;
    velocity = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    velocity |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);
    dst_p->velocity = (int32_t)velocity;

    return (0);
}

int mcan_m_ref_2_init(struct mcan_m_ref_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_ref_2_t));

    return 0;
}

int32_t mcan_m_ref_2_position_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_ref_2_position_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_ref_2_position_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t mcan_m_ref_2_velocity_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_ref_2_velocity_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_ref_2_velocity_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int mcan_m_pos_vel_2_pack(
    uint8_t *dst_p,
    const struct mcan_m_pos_vel_2_t *src_p,
    size_t size)
{
    uint32_t position;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint32_t)src_p->position;
    dst_p[0] |= pack_right_shift_u32(position, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(position, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(position, 0u, 0xffu);
    velocity = (uint32_t)src_p->velocity;
    dst_p[4] |= pack_right_shift_u32(velocity, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(velocity, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(velocity, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(velocity, 0u, 0xffu);

    return (8);
}

int mcan_m_pos_vel_2_unpack(
    struct mcan_m_pos_vel_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t position;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    position |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    position |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->position = (int32_t)position;
    velocity = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    velocity |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);
    dst_p->velocity = (int32_t)velocity;

    return (0);
}

int mcan_m_pos_vel_2_init(struct mcan_m_pos_vel_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_pos_vel_2_t));

    return 0;
}

int32_t mcan_m_pos_vel_2_position_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_pos_vel_2_position_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_pos_vel_2_position_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t mcan_m_pos_vel_2_velocity_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_pos_vel_2_velocity_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_pos_vel_2_velocity_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int mcan_m_diag_2_pack(
    uint8_t *dst_p,
    const struct mcan_m_diag_2_t *src_p,
    size_t size)
{
    uint32_t er;
    uint32_t reg_out;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    reg_out = (uint32_t)src_p->reg_out;
    dst_p[0] |= pack_right_shift_u32(reg_out, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(reg_out, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(reg_out, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(reg_out, 0u, 0xffu);
    er = (uint32_t)src_p->er;
    dst_p[4] |= pack_right_shift_u32(er, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(er, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(er, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(er, 0u, 0xffu);

    return (8);
}

int mcan_m_diag_2_unpack(
    struct mcan_m_diag_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t er;
    uint32_t reg_out;

    if (size < 8u) {
        return (-EINVAL);
    }

    reg_out = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    reg_out |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    reg_out |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    reg_out |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->reg_out = (int32_t)reg_out;
    er = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    er |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    er |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    er |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);
    dst_p->er = (int32_t)er;

    return (0);
}

int mcan_m_diag_2_init(struct mcan_m_diag_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mcan_m_diag_2_t));

    return 0;
}

int32_t mcan_m_diag_2_reg_out_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_diag_2_reg_out_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_diag_2_reg_out_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t mcan_m_diag_2_er_encode(float value)
{
    return (int32_t)(value / 0.001f);
}

float mcan_m_diag_2_er_decode(int32_t value)
{
    return ((float)value * 0.001f);
}

bool mcan_m_diag_2_er_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}
